---
blank_issues_enabled: false
contact_links:
  - name: AccountingExamsMastery.ca Community Support
    url: https://github.com/MasteryEducation/AccountingExamsMastery.ca/discussions
    about: Please ask and answer questions here.
